catalog/urls.py
# catalog/urls.py

from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^books/$', views.BookListView.as_view(), name='books'),
	url(r'^books/(?P<slug>[-\w]+)$', views.BookDetailView.as_view(), name='book-detail'), # pk -> slug; d+ -> [-\w]+
	url(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
	url(r'^authors/(?P<slug>[-\w]+)$', views.AuthorDetailView.as_view(), name='author-details'),
]

locallibrary/urls.py
# *** NB: separating out all add-ons because this is a tutorial
# -> IRL would probably import all at once and write one list ***

from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]
# above: default configuration

# below: send URLs ending in /catalog to the catalog app's URL module
from django.conf.urls import include

urlpatterns += [
	url(r'^catalog/', include('catalog.urls')),
]

# below: redirect root URL to catalog application when loads
from django.views.generic import RedirectView

urlpatterns += [
	url(r'^$', RedirectView.as_view(url='/catalog', permanent=True)),
]

# below: enable serving static files during development

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
# models for locallibrary

from django.db import models
from django.urls import reverse
import uuid

# Genre: (list skeleton/maker)
class Genre(models.Model):
	name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Historical Fiction)")

	def __str__(self):
		return self.name

# Book: (title, not physical object)
class Book(models.Model):
	title = models.CharField(max_length=200)
	author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
	summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book.")
	isbn = models.CharField('ISBN', max_length=13, 
		help_text='Enter the 13-digit <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
	genre = models.ManyToManyField(Genre, help_text="Please choose one or more genres for this title.")
	# MDN challenge:
	language = models.ManyToManyField('Language', help_text="Languages available for this title")
	slug = models.SlugField(unique=True) # removed: 'default=uuid.uuid4' from creating slug field

	class Meta:
		ordering = ['title']

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('book-detail', args=[self.slug]) # 'self.id' -> 'self.slug'
		# we need to write URL handler called 'book-details'
		# also create template for handler to use
		# (basically an artifact entry page)

	# for BookAdmin:
	def display_genre(self):
		return ", ".join ( [genre.name for genre in self.genre.all()[:3]] )
		# returns 'genre1, genre2, genre3' for the names listed in the book's return object for its 'genre' field
		# Book.genre is ManyToManyField object, so must be turned into string first
	display_genre.short_description = 'Genre'
	# above: can be used in admin site w/ this method

# BookInstance: (physical object)
class BookInstance(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this book copy.")
	book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
	imprint = models.CharField(max_length=200) # ???
	due_back = models.DateField(null=True, blank=True) # null/blank when book not checked out
	# MDN challenge:
	language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

	LOAN_STATUS = (
		('m', 'Maintenance'),
		('o', 'On loan'),
		('r', 'Reserved'),
		('a', 'Available'),
	) # ('db val', 'Display Text')

	status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

	class Meta:
		ordering = ["due_back"]

	def __str__(self):
		return '{0} ({1})'.format(self.id, self.book.title)

# Author:
class Author(models.Model):
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	date_of_birth = models.DateField(null=True, blank=True)
	date_of_death = models.DateField('Died', null=True, blank=True) # 1st arg = verbose_name
	slug = models.SlugField(unique=True)

	def get_absolute_url(self):
		return reverse('author-details', args=[self.slug])

	def __str__(self):
		return '{0}, {1}'.format(self.last_name, self.first_name)

# Language: (list of all languages in library, subject to change so is model)
class Language(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

catalog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Book, BookInstance, Author, Genre

def index(request):
	num_books = Book.objects.count()
	num_instances = BookInstance.objects.count()
	num_instances_available = BookInstance.objects.filter(status__exact='a').count()
	num_authors = Author.objects.count()

	return render(
		request,
		'index.html',
		context={'num_books':num_books, 'num_instances':num_instances, 
		'num_instances_available':num_instances_available, 'num_authors':num_authors},
	)

class BookListView(generic.ListView):
	model = Book
	paginate_by = 2

class BookDetailView(generic.DetailView):
	model = Book

class AuthorListView(generic.ListView):
	model = Author

class AuthorDetailView(generic.DetailView):
	model = Author

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'books' %}">All books</a></li> <!-- the name we set in url() function -->
          <li><a href="{% url 'authors' %}">All authors</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}

      {% block pagination %}
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
      {% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h2> {{author.first_name}} {{author.last_name}}</h2>

<ul><strong>Works:</strong>
  {% for book in author.book_set.all %}
  <li>{{book.title}}</li>
  {% endfor %}
</ul>

{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Authors</h1>

<ul>
{% for author in author_list %}
<li><a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a></li>
{% endfor %}
</ul>

{% endblock %}

catalog/templates/catalog/book_detail.html
<!-- autonaming scheme: modelname_genericviewname.html -->
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p>
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> insert language</p>
  <p><strong>Genre:</strong>{% for genre in book.genre.all %} {{genre}}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %} <!-- builtin b/c BI has foreignkey w/ book -->
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}"> {{copy.get_status_display}}</p>
    <!-- confused: when did these things get defined? ^ -->
    {% if copy.status != 'a' %}<p><strong>Due back:</strong> {{ copy.due_back }}</p>{% endif %}
    <p><strong>Imprint:</strong> insert imprint</p> <!-- not adding b/c unsure what it does if prop undefined -->
    <p class="text-muted"><strong>ID:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
<!-- book_list.html -->
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>

  {% if book_list %} <!-- is defined and not empty -->
  <ul>
    {% for book in book_list %}
    <li>
      <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
      <!-- NB: these urls^ don't exist yet; must create book detail page for template to load! -->
    </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block title %}<title>Home - Local Library</title>{% endblock %}

{% block content %}
<h1>Local Library Home</h1>

  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>

<h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>
{% endblock %}